return {
    name = 'Hexagon',
    {
        segments = 6,
        blocks = {
            {position = 1, offset = 0},
            {position = 2, offset = 0},
            {position = 3, offset = 0},
            {position = 4, offset = 4},
            {position = 5, offset = 4},
            {position = 6, offset = 4},
            {position = 1, offset = 8},
            {position = 2, offset = 8},
            {position = 3, offset = 8},
            {position = 4, offset = 12},
            {position = 5, offset = 12},
            {position = 6, offset = 12},
            {position = 1, offset = 16},
            {position = 2, offset = 16},
            {position = 3, offset = 16},
            {position = 4, offset = 20},
            {position = 5, offset = 20},
            {position = 6, offset = 20}
        }
    },
    {
        segments = 6,
        blocks = {
            {position = 1, offset = 0},
            {position = 2, offset = 0},
            {position = 3, offset = 0},
            {position = 4, offset = 0},
            {position = 5, offset = 0},
            {position = 2, offset = 6},
            {position = 3, offset = 6},
            {position = 4, offset = 6},
            {position = 5, offset = 6},
            {position = 6, offset = 6},
            {position = 3, offset = 12},
            {position = 4, offset = 12},
            {position = 5, offset = 12},
            {position = 6, offset = 12},
            {position = 7, offset = 12},
            {position = 4, offset = 18},
            {position = 5, offset = 18},
            {position = 6, offset = 18},
            {position = 7, offset = 18},
            {position = 8, offset = 18},
            {position = 5, offset = 24},
            {position = 6, offset = 24},
            {position = 7, offset = 24},
            {position = 8, offset = 24},
            {position = 9, offset = 24},
            {position = 6, offset = 30},
            {position = 7, offset = 30},
            {position = 8, offset = 30},
            {position = 9, offset = 30},
            {position = 10, offset = 30}
        }
    },
    {
        segments = 6,
        blocks = {
            {position = 1, offset = 0},
            {position = 4, offset = 0},
            {position = 2, offset = 3},
            {position = 5, offset = 3},
            {position = 3, offset = 6},
            {position = 6, offset = 6},
            {position = 1, offset = 9},
            {position = 4, offset = 9},
            {position = 2, offset = 12},
            {position = 5, offset = 12},
            {position = 3, offset = 15},
            {position = 6, offset = 15},
            {position = 1, offset = 18},
            {position = 4, offset = 18},
            {position = 2, offset = 21},
            {position = 5, offset = 21},
            {position = 3, offset = 24},
            {position = 6, offset = 24}
        }
    },
    {
        segments = 6,
        blocks = {
            {position = 1, offset = 0},
            {position = 1, offset = 1},
            {position = 2, offset = 2},
            {position = 2, offset = 3},
            {position = 3, offset = 4},
            {position = 3, offset = 5},
            {position = 4, offset = 6},
            {position = 4, offset = 7},
            {position = 5, offset = 8},
            {position = 5, offset = 9},
            {position = 6, offset = 10},
            {position = 6, offset = 11},
            {position = 7, offset = 13},
            {position = 7, offset = 12},
            {position = 8, offset = 14},
            {position = 8, offset = 15},
            {position = 9, offset = 16},
            {position = 9, offset = 17},
            {position = 10, offset = 18},
            {position = 10, offset = 19},
            {position = 11, offset = 20},
            {position = 11, offset = 21},
            {position = 12, offset = 22},
            {position = 12, offset = 23},
            {position = 13, offset = 24},
            {position = 13, offset = 25},
            {position = 14, offset = 26},
            {position = 14, offset = 27},
            {position = 15, offset = 28},
            {position = 15, offset = 29}
        }
    }
}
